
FirstNameOfWitness="Annabel" 
LastNameOfWitness="Church"
InterviewNumber="699607"
Car="Blue Honda"
FirstNameOfSuspect1="Aron" 
LastNameOfSuspect1="Pilhofer"
FirstNameOfSuspect2="Joe" 
LastNameOfSuspect2="Germuska"
FirstNameOfSuspect3="Mike"
LastNameOfSuspect3="Bostock"

printf "$FirstNameOfWitness $LastNameOfWitness\n"
printf "$InterviewNumber\n"
printf "$Car\n"
printf "$FirstNameOfSuspect1 $LastNameOfSuspect1\n"
printf "$FirstNameOfSuspect2 $LastNameOfSuspect2\n"
printf "$FirstNameOfSuspect3 $LastNameOfSuspect3\n"
